ECommerceProject/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Brand
    {
        public int Id { get; set; }
        [Required,StringLength(100)]
        public string Name { get; set; }
        public string Country { get; set; }
    }
}

ECommerceProject/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required,StringLength(100)]
        public string Name { get; set; }
    }
}

ECommerceProject/Models/Configuration.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Configuration
    {
        public int Id { get; set; }
        [Required, StringLength(500)]
        public string Name { get; set; }
    }
}

ECommerceProject/Models/Customer.cs
namespace ECommerceProject.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set;}
        public string ContactNo { get; set;}
        public string Email { get; set;}
        public string Address { get; set;}

    }
}

ECommerceProject/Models/ErrorViewModel.cs
namespace ECommerceProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerceProject/Models/Model.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Model
    {
        public int Id { get; set; }
        [Required,StringLength(100)]
        public string Name { get; set; }
    }
}

ECommerceProject/Models/Product.cs
namespace ECommerceProject.Models
{
    public class Product
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public int ModelId { get; set; }
        public int ConfigurationId { get; set; }
        public string ProdCode { get; set; }
        public Boolean IsActive { get; set; }
        public float SalePrice { get; set; }
        public int WarnPoint { get; set; }
        public int Warranty { get; set; }
        public DateTime CreateDate { get; set; }
        public float Vat { get; set; }
        public DateTime UpdateDate { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public string ProductNM { get; set; }
        public Boolean IsDiscount { get; set; }
        public float DiscountAMT { get; set; }
    }
}

ECommerceProject/Models/ProductImage.cs
namespace ECommerceProject.Models
{
    public class ProductImage
    {
        public int Id { get; set; }
        public int ProdId { get; set; }
        public string ImageName { get; set; }
        public string ImageCode { get; set; }
        public float ImageSize { get; set; }
    }
}

ECommerceProject/Models/Purchase.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Purchase
    {
        public int Id { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime InvoiceDate { get; set; }
        [Required]
        public string InvoiceNo { get; set; }
        [Required]
        public int ProdId { get; set; }
        public float PurchasePrice { get; set; }
        public int PurchaseQTY { get; set; }
        public int UnitId { get; set; }
        public int VendorId { get; set; }
    }
}

ECommerceProject/Models/SalesDetail.cs
namespace ECommerceProject.Models
{
    public class SalesDetail
    {
        public int Id { get; set; }
        public int SalesOrdId { get; set; }
        public int ProdId { get; set; }
        public string ProdUnit { get; set; }
        public float UnitPrice { get; set; }
        public int SaleQty { get; set; }
    }
}

ECommerceProject/Models/SalesOrder.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class SalesOrder
    {
        public int Id { get; set; }
        [Required,DataType(DataType.Date)]
        public DateTime InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public int CustomerID { get; set; }
        public float TotalBillAmt { get; set; }
        public float Discount { get; set; }
        public float Vat { get; set; }
        public float ShippingCharge { get; set; }
        public float NetPayable { get; set; }
        public string Remarks { get; set; }
    }
}

ECommerceProject/Models/Stock.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Stock
    {
        public int Id { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime StockDate { get; set; }
        public int ProdId { get; set; }
        public int StockIn { get; set; }
        public int StockOut { get; set; }
        public int StockBalance { get; set; }

    }
}

ECommerceProject/Models/SubCategory.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class SubCategory
    {
        public int Id { get; set; }
        [Required,StringLength(100)]
        public string Name { get; set; }
        public int CategoryID { get; set; }
    }
}

ECommerceProject/Models/Vendor.cs
using System.ComponentModel.DataAnnotations;

namespace ECommerceProject.Models
{
    public class Vendor
    {
        public int Id { get; set; }
        [Required, StringLength(150)]
        public string Name { get; set; }
        public string Address { get; set; }

    }
}

ECommerceProject/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerceProject.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WishList()
        {
            return View();
        }
        public IActionResult ShoppingCart()
        {
            return View();
        }
        public IActionResult Checkout()
        {
            return View();
        }
    }
}

ECommerceProject/Controllers/HomeController.cs
using ECommerceProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerceProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
		}
		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerceProject/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerceProject.Controllers
{
    public class PaymentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PaymentGateway()
        {
            return View();
        }
    }
}

ECommerceProject/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerceProject.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProductView()
        {
            return View();
        }
    }
}

ECommerceProject/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace ECommerceProject.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShopGrid()
        {
            return View();
        }
    }
}

ECommerceProject/Views/Cart/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}

<!-- breadcum start -->
<div class="breadcum">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="d-flex align-items-center gap-2">
					<a asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 20px; color: #67bccd"><i class="las la-home"></i></a>
					<span style="font-size: 14px; color: #67bccd"><i class="las la-chevron-right"></i></span>
					<p class="mb-0" style="font-size: 16px;">Checkout</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- breadcum end -->

<!-- checkout start -->
<div class="checkout">
	<div class="container">
		<div class="row">

            <!-- checkout form -->
			<div class="col-md-8">
				<h4 class="checkout_cart_title mb-4 ps-3">Billing details</h4>
				<div class="checkout_form">
					<div class="billing_form">
						<div class="row gy-3">
							<div class="col-lg-6">
								<div class="single_billing_inp">
									<label for="first_name">First Name <span>*</span></label>
									<input type="text" id="first_name">
								</div>
							</div>
							<div class="col-lg-6">
								<div class="single_billing_inp">
									<label for="last_name">Last Name <span>*</span></label>
									<input type="text" id="last_name">
								</div>
							</div>
							<div class="col-12">
								<div class="single_billing_inp">
									<label for="company_name">Holding No/ Company Name <span>*</span></label>
									<input type="text" id="company_name">
								</div>
							</div>
							<div class="col-6">
								@* <div class="single_billing_inp">
									<label for="county_region">County/Region <span>*</span></label>
									<input type="text" id="county_region">
								</div> *@
								<div class="single_billing_inp">
									<label for="county_region">County/Region <span>*</span></label>
									<select class="form-select" aria-label="Default select example">
										<option value="1">Bangladesh</option>
										<option value="2">Uk</option>
										<option value="3">USA</option>
									</select>
								</div>
							</div>
							<div class="col-6">
								@* <div class="single_billing_inp">
									<label for="town_city">Town/City <span>*</span></label>
									<input type="text" id="town_city">
								</div> *@
								<div class="single_billing_inp">
									<label for="town_city">Town/City <span>*</span></label>
									<select class="form-select" aria-label="Default select example">
										<option value="1">Dhaka</option>
										<option value="2">Narayanganj</option>
										<option value="3">Kushtia</option>
									</select>
								</div>
							</div>
							<div class="col-12">
								<div class="single_billing_inp">
									<label for="street_addr">Street Address <span>*</span></label>
									<input type="text" id="street_addr">
								</div>
							</div>
							<div class="col-12">
								<div class="single_billing_inp">
									<label for="zip_code">Zip Code <span>*</span></label>
									<input type="text" id="zip_code">
								</div>
							</div>
							<div class="col-12">
								<div class="single_billing_inp">
									<label for="phone_number">Phone Number <span>*</span></label>
									<input type="text" id="phone_number">
								</div>
							</div>
							<div class="col-12">
								<div class="single_billing_inp">
									<label for="email_addr">Email Address <span>*</span></label>
									<input type="text" id="email_addr">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
            <!-- checkout form end -->

            <!-- sidebar -->
			<div class="col-md-4">
				<h4 class="checkout_cart_title ps-3">Your order</h4>
				<div class="checkout_order">
					<h4>product</h4>
					<div class="single_check_order">
						<div class="checkorder_cont">
							<h5>Italian Chair</h5>
							<p>
								<span>Size: M</span>
								<span>Color: Red</span>
							</p>
						</div>
						<p class="checkorder_qnty">x1</p>
						<p class="checkorder_price">$1084.90</p>
					</div>
					<div class="single_check_order">
						<div class="checkorder_cont">
							<h5>Resting Bed</h5>
							<p>
								<span>Size: M</span>
								<span>Color: Red</span>
							</p>
						</div>
						<p class="checkorder_qnty">x2</p>
						<p class="checkorder_price">$84.00</p>
					</div>
					<div class="single_check_order">
						<div class="checkorder_cont">
							<h5>Air Bed</h5>
							<p>
								<span>Size: M</span>
								<span>Color: Red</span>
							</p>
						</div>
						<p class="checkorder_qnty">x1</p>
						<p class="checkorder_price">$84.00</p>
					</div>
					<div class="single_check_order subs">
						<div class="checkorder_cont subtotal-h">
							<h5>Subtotal</h5>
						</div>
						<p class="checkorder_price">$140.00</p>
					</div>
					<div class="single_check_order subs">
						<div class="checkorder_cont subtotal-h">
							<h5>Shipping</h5>
						</div>
						<p class="checkorder_price" style="color: green;">Free</p>
					</div>
					<div class="single_check_order total">
						<div class="checkorder_cont">
							<h5>Total</h5>
						</div>
						<p class="checkorder_price fw-bold">$140.00</p>
					</div>
					<div class="checkorder_agree">
						<input type="checkbox" class="check_inp" id="save-default">
						<label for="save-default">Agree to our <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-color">terms &amp; conditions</a></label>
					</div>

					<div class="checkorder_btn">
						<a href="#" class="default_btn1 text-uppercase" style="font-weight: 500;">Place Order</a>
					</div>
				</div>
			</div>
			<!-- sidebar end -->

		</div>
	</div>
</div>
<!-- checkout end -->

ECommerceProject/Views/Cart/ShoppingCart.cshtml
@{
    ViewData["Title"] = "ShoppingCart";
}

<!-- breadcum start -->
<div class="breadcum">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex align-items-center gap-2">
                    <a asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 20px; color: #67bccd"><i class="las la-home"></i></a>
                    <span style="font-size: 14px; color: #67bccd"><i class="las la-chevron-right"></i></span>
                    <p class="mb-0" style="font-size: 16px;">Shopping Cart</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcum end -->

<!-- cart wrapper start -->
<div class="shop-cart mt-4">
    <div class="container">
        <div class="row">
            <!-- product card start -->
            <div class="col-md-9">
                <div class="shop_cart_wrap">

                    <!-- single cart -->
                    <div class="single_shop_cart mb-4">

                        <!-- cart image -->
                        <div class="cart_img mb-4 mb-md-0"><img loading="lazy" src="~/images/products/product9.jpg" alt="product"></div>

                        <!-- cart content -->
                        <div class="cart_content">
                            <a asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Italian L Shape Sofa</h5></a>
                            <p class="price">$45.00</p>
                            <p class="size">Size: M</p>
                        </div>

                        <!-- cart quantity -->
                        <div class="cart_qnty">
                            <button class="cart_qnty_btn"><i class="las la-minus"></i></button>
                            <div class="cart_count">4</div>
                            <button class="cart_qnty_btn"><i class="las la-plus"></i></button>
                        </div>

                        <!-- cart price -->
                        <div class="cart_price ms-auto"><p>$1045.99</p></div>

                        <!-- cart remove icon -->
                        <div class="cart_remove ms-auto"><i class="las la-trash"></i></div>

                    </div>

                    <!-- single cart -->
                    <div class="single_shop_cart mb-4">

                        <!-- cart image -->
                        <div class="cart_img mb-4 mb-md-0"><img loading="lazy" src="~/images/products/product3.jpg" alt="product"></div>

                        <!-- cart content -->
                        <div class="cart_content">
                            <a asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Air Bed</h5></a>
                            <p class="price">$45.00</p>
                            <p class="size">Size: XL</p>
                        </div>

                        <!-- cart quantity -->
                        <div class="cart_qnty">
                            <button class="cart_qnty_btn"><i class="las la-minus"></i></button>
                            <div class="cart_count">6</div>
                            <button class="cart_qnty_btn"><i class="las la-plus"></i></button>
                        </div>

                        <!-- cart price -->
                        <div class="cart_price ms-auto"><p>$1045.99</p></div>

                        <!-- cart remove icon -->
                        <div class="cart_remove ms-auto"><i class="las la-trash"></i></div>

                    </div>

                    <!-- single cart -->
                    <div class="single_shop_cart mb-4">

                        <!-- cart image -->
                        <div class="cart_img mb-4 mb-md-0"><img loading="lazy" src="~/images/products/product2.jpg" alt="product"></div>

                        <!-- cart content -->
                        <div class="cart_content">
                            <a asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Dashing Sofa</h5></a>
                            <p class="price">$140.00</p>
                            <p class="size">Size: M</p>
                        </div>

                        <!-- cart quantity -->
                        <div class="cart_qnty">
                            <button class="cart_qnty_btn"><i class="las la-minus"></i></button>
                            <div class="cart_count">2</div>
                            <button class="cart_qnty_btn"><i class="las la-plus"></i></button>
                        </div>

                        <!-- cart price -->
                        <div class="cart_price ms-auto"><p>$1045.99</p></div>

                        <!-- cart remove icon -->
                        <div class="cart_remove ms-auto"><i class="las la-trash"></i></div>

                    </div>

                </div>

            </div>
            <!-- product card end -->

            <!-- order summary -->
            <div class="col-md-3">
                <div class="cart_summary">
                    <h4>Order Summary</h4>
                    <div class="cartsum_text">
                        <p style="font-weight: 500;">Subtotal</p>
                        <p style="font-weight: 500;">$45.00</p>
                    </div>
                    <div class="cartsum_text">
                        <p>Delivery</p>
                        <p>Free</p>
                    </div>
                    <div class="cartsum_text">
                        <p>Tax</p>
                        <p>$5.00</p>
                    </div>
                    <div class="cart_sum_total">
                        <p>Total</p>
                        <p>$50.00</p>
                    </div>
                    <div class="cart_sum_pros_btn">
                        <a asp-area="" asp-controller="Cart" asp-action="Checkout" class="default_btn1 text-uppercase" style="font-weight: 500;">Proccees to checkout</a>
                    </div>
                </div>
            </div>
            <!-- order summary end -->
        </div>
    </div>
</div>
<!-- card wrapper end -->

ECommerceProject/Views/Cart/WishList.cshtml
@{
    ViewData["Title"] = "WishList";
}

<!-- breadcum start -->
<div class="breadcum">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="d-flex align-items-center gap-2">
                    <a asp-area="" asp-controller="Home" asp-action="Index" style="font-size: 20px; color: #67bccd"><i class="las la-home"></i></a>
                    <span style="font-size: 14px; color: #67bccd"><i class="las la-chevron-right"></i></span>
                    <p class="mb-0" style="font-size: 16px;">Wish List</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcum end -->

<div class="wishlist">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                
                <!-- single wishlist -->
                <div class="single_wishlist">

                    <!-- cart image -->
                    <div class="cart_img"><img loading="lazy" src="~/images/products/product9.jpg" alt="product"></div>

                    <!-- cart content -->
                    <div class="cart_cont">
                        <a target="_blank" asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Cuision Relax Rocking Chair</h5></a>
                        <p class="instock">Availability: <span>In Stock</span></p>
                    </div>

                    <!-- cart price -->
                    <div class="cart_price"><p>$45.00</p></div>

                    <!-- add to cart button -->
                    <div class="wish_cart_btn">
                        @* <a asp-area="" asp-controller="Cart" asp-action="ShoppingCart" class="default_btn1">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </a> *@
                        <button class="default_btn1">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </button>
                    </div>

                    <!-- cart remove icon -->
                    <div class="cart_remove"><i class="las la-trash"></i></div>
                </div>

                <!-- single wishlist -->
                <div class="single_wishlist">

                    <!-- cart image -->
                    <div class="cart_img"><img loading="lazy" src="~/images/products/product11.jpg" alt="product"></div>

                    <!-- cart content -->
                    <div class="cart_cont">
                        <a target="_blank" asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Resting Bed</h5></a>
                        <p class="outstock">Availability: <span>Out of Stock</span></p>
                    </div>

                    <!-- cart price -->
                    <div class="cart_price"><p>$45.00</p></div>

                    <!-- add to cart button -->
                    <div class="wish_cart_btn">
                        <button class="default_btn1 disabled">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </button>
                    </div>

                    <!-- cart remove icon -->
                    <div class="cart_remove"><i class="las la-trash"></i></div>
                </div>

                <!-- single wishlist -->
                <div class="single_wishlist">

                    <!-- cart image -->
                    <div class="cart_img"><img loading="lazy" src="~/images/products/product6.jpg" alt="product"></div>

                    <!-- cart content -->
                    <div class="cart_cont">
                        <a target="_blank" asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Relax Chair</h5></a>
                        <p class="instock">Availability: <span>In Stock</span></p>
                    </div>

                    <!-- cart price -->
                    <div class="cart_price"><p>$45.00</p></div>

                    <!-- add to cart button -->
                    <div class="wish_cart_btn">
                        @* <a asp-area="" asp-controller="Cart" asp-action="ShoppingCart" class="default_btn1">
                        <span class="icon">
                        <i class="cart_icon las la-cart-arrow-down"></i>
                        </span> Add to Cart
                        </a> *@
                        <button class="default_btn1">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </button>
                    </div>

                    <!-- cart remove icon -->
                    <div class="cart_remove"><i class="las la-trash"></i></div>
                </div>

                <!-- single wishlist -->
                <div class="single_wishlist">

                    <!-- cart image -->
                    <div class="cart_img"><img loading="lazy" src="~/images/products/product3.jpg" alt="product"></div>

                    <!-- cart content -->
                    <div class="cart_cont">
                        <a target="_blank" asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Air Bed</h5></a>
                        <p class="instock">Availability: <span>In Stock</span></p>
                    </div>

                    <!-- cart price -->
                    <div class="cart_price"><p>$45.00</p></div>

                    <!-- add to cart button -->
                    <div class="wish_cart_btn">
                        @* <a asp-area="" asp-controller="Cart" asp-action="ShoppingCart" class="default_btn1">
                        <span class="icon">
                        <i class="cart_icon las la-cart-arrow-down"></i>
                        </span> Add to Cart
                        </a> *@
                        <button class="default_btn1">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </button>
                    </div>

                    <!-- cart remove icon -->
                    <div class="cart_remove"><i class="las la-trash"></i></div>
                </div>

                <!-- single wishlist -->
                <div class="single_wishlist">

                    <!-- cart image -->
                    <div class="cart_img"><img loading="lazy" src="~/images/products/product12.jpg" alt="product"></div>

                    <!-- cart content -->
                    <div class="cart_cont">
                        <a target="_blank" asp-area="" asp-controller="Product" asp-action="ProductView"><h5>Show Piece Table</h5></a>
                        <p class="outstock">Availability: <span>Out of Stock</span></p>
                    </div>

                    <!-- cart price -->
                    <div class="cart_price"><p>$45.00</p></div>

                    <!-- add to cart button -->
                    <div class="wish_cart_btn">
                        <button class="default_btn1 disabled">
                            <span class="icon">
                                <i class="cart_icon las la-cart-arrow-down"></i>
                            </span> Add to Cart
                        </button>
                    </div>

                    <!-- cart remove icon -->
                    <div class="cart_remove"><i class="las la-trash"></i></div>
                </div>
            
            </div>
        </div>
    </div>
</div>

ECommerceProject/Views/Payment/PaymentGateway.cshtml
@{
    ViewData["Title"] = "PaymentGateway";
}

<h1>PaymentGateway</h1>

ECommerceProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerceProject</title>
    <!-- Line Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css" integrity="sha512-vebUliqxrVkBy3gucMhClmyQP9On/HAWQdKDXRaAlb/FKuTbxkjPKUyqVOxAcGwFDka79eTF+YXwfke1h3/wfg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerceProject.styles.css" asp-append-version="true" />
</head>
<body>

    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" asp-area="" asp-controller="Home" asp-action="Index">E-Commerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="ShopGrid">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="WishList">Wish List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ShoppingCart">Cart</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <!-- Header End -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <span class="fw-bold" style="color: #67bccd;">&copy;</span> 2024 - ECommerceProject
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>